Fix typo in handler-ponymailer.rb
Causing error bin/handler-ponymailer.rb:46:in `handle': undefined method `e!' for #<PonyMailer:0x00000002353ae8> (NoMethodError)